In [1]:
#INTRINSIC CREATION OF ARRAYS
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [2]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
np.arange(4,10,3)

array([4, 7])

In [31]:
a = np.random.random((3,3,3))
a

array([[[0.79229205, 0.04299545, 0.28498782],
        [0.45083595, 0.46007569, 0.21882232],
        [0.83216874, 0.66258968, 0.06519101]],

       [[0.69426054, 0.71653106, 0.47797054],
        [0.4034443 , 0.94611489, 0.28798737],
        [0.29045246, 0.34951501, 0.35203971]],

       [[0.8861745 , 0.11349502, 0.1232309 ],
        [0.76371642, 0.84919374, 0.94689647],
        [0.32519463, 0.36506257, 0.90035816]]])

In [32]:
a[0][2][1]

0.6625896756151506

In [33]:
li =[1,2,3,4,5]
type(li)

list

In [38]:
li_arr = np.array(li)
li_arr
type(li_arr)

numpy.ndarray

In [39]:
li_arr.dtype

dtype('int64')

In [40]:
li_arr.ndim

1

In [41]:
li_arr.size

5

In [42]:
li_arr.itemsize


8

In [43]:
li_arr.data

In [52]:
#CREATE ARRAY FROM SET
d = np.array(((1, 2, 3),(4, 5, 6)))

In [47]:
d.shape

(2, 3)

In [48]:
d.size

6

In [49]:
d.data

In [50]:
d.itemsize

8

In [53]:
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])

e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
type(e)

numpy.ndarray

In [56]:
f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])