In [1]:
#INTRINSIC CREATION OF ARRAYS
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [2]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
np.arange(4,10,3)

array([4, 7])

In [5]:
a = np.random.random((3,3,3))
a

array([[[0.87718789, 0.86876131, 0.60854124],
        [0.82046488, 0.90694955, 0.10279181],
        [0.45099566, 0.29874876, 0.04480403]],

       [[0.20795943, 0.15908244, 0.27469673],
        [0.46746929, 0.04350881, 0.91107522],
        [0.92992187, 0.045352  , 0.13972001]],

       [[0.89364433, 0.444786  , 0.34623596],
        [0.5558632 , 0.46413103, 0.53485653],
        [0.09135364, 0.15469934, 0.27307825]]])

In [6]:
a[0][2][1]

0.29874876309205656

In [7]:
li =[1,2,3,4,5]
type(li)

list

In [8]:
li_arr = np.array(li)
li_arr
type(li_arr)

numpy.ndarray

In [9]:
li_arr.dtype

dtype('int64')

In [10]:
li_arr.ndim

1

In [11]:
li_arr.size

5

In [12]:
li_arr.itemsize


8

In [13]:
li_arr.data

In [14]:
#CREATE ARRAY FROM SET
d = np.array(((1, 2, 3),(4, 5, 6)))

In [15]:
d.shape

(2, 3)

In [16]:
d.size

6

In [17]:
d.data

In [18]:
d.itemsize

8

In [19]:
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])

e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
type(e)

numpy.ndarray

In [21]:
f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

# BASIC OPERATIONS

In [27]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
a+4

array([4, 5, 6, 7, 8])

In [30]:
a*2

array([0, 2, 4, 6, 8])

In [35]:
b= np.arange(4,9)
b

array([4, 5, 6, 7, 8])

In [36]:
a+b

array([ 4,  6,  8, 10, 12])

In [37]:
a-b

array([-4, -4, -4, -4, -4])

In [38]:
a/b

array([0.        , 0.2       , 0.33333333, 0.42857143, 0.5       ])

In [39]:
a * b

array([ 0,  5, 12, 21, 32])

In [40]:
a % b

array([0, 1, 2, 3, 4])

In [41]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ,  3.95743299])

In [42]:
a * np.sqrt(b)

array([ 0.        ,  2.23606798,  4.89897949,  7.93725393, 11.3137085 ])

In [43]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
A * B 


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [46]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

# AGGREGATE FUNCTIONS

In [47]:
a= np.array([3.2,4.5,1.2,5.7,0.1])

In [48]:
a.sum()

14.700000000000001

In [49]:
a.min()

0.1

In [50]:
a.max()

5.7

In [51]:
a.mean()

2.9400000000000004

In [53]:
a.std()

2.0597087172704787

# INDEXING, SLICING, ITERATING

In [57]:
a =np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [56]:
a[4]

14

In [58]:
a[-1]

15

In [59]:
a[-6]

10

In [60]:
a[[1, 3, 4]]

array([11, 13, 14])

In [61]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [62]:
A[1, 2]


15

In [64]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [65]:
a[1:5]

array([11, 12, 13, 14])

In [66]:
a[1:5:2]

array([11, 13])

In [67]:
a[::2]

array([10, 12, 14])

In [68]:
 a[:5:2]

array([10, 12, 14])

In [69]:
 a[:5:]

array([10, 11, 12, 13, 14])

In [71]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [72]:
A[0,:]

array([10, 11, 12])

In [80]:
A[:,0]

array([10, 13, 16])

In [81]:
A[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [77]:
for i in a:
    print(i)

10
11
12
13
14
15


In [79]:
for row in A:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [82]:
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


In [86]:
np.apply_along_axis(func1d=np.sum,axis=0,arr=A)

array([39, 42, 45])

In [88]:
np.apply_along_axis(func1d = np.sum,axis=1,arr =A )

array([33, 42, 51])

In [89]:
c = np.append(a,b)
c

array([10, 11, 12, 13, 14, 15,  4,  5,  6,  7,  8])

In [92]:
def func(x):
    print(x)
    return x

In [91]:
np.apply_along_axis(func1d=func,axis=0,arr=A)

[10 13 16]
[11 14 17]
[12 15 18]


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [94]:
A = np.random.random((4,4))
A

array([[0.18127785, 0.60780153, 0.89589008, 0.53352314],
       [0.71748994, 0.76709002, 0.49441204, 0.82598396],
       [0.79189916, 0.07218789, 0.9555812 , 0.65320457],
       [0.41793407, 0.21277199, 0.2833243 , 0.5918972 ]])

In [95]:
A.shape

(4, 4)

In [96]:
A.size

16

In [97]:
A.data

In [98]:
A.dtype

dtype('float64')

In [99]:
A < 0.5

array([[ True, False, False, False],
       [False, False,  True, False],
       [False,  True, False, False],
       [ True,  True,  True, False]])

In [101]:
A[A<0.5]

array([0.18127785, 0.49441204, 0.07218789, 0.41793407, 0.21277199,
       0.2833243 ])

In [104]:
B = A.ravel()

In [105]:
B.shape

(16,)

In [107]:
C = A.transpose()
C

array([[0.18127785, 0.71748994, 0.79189916, 0.41793407],
       [0.60780153, 0.76709002, 0.07218789, 0.21277199],
       [0.89589008, 0.49441204, 0.9555812 , 0.2833243 ],
       [0.53352314, 0.82598396, 0.65320457, 0.5918972 ]])

# Array Manipulation

In [108]:
#joining Arrays
A = np.ones((3, 3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [109]:
B = np.zeros((3, 3))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [117]:
C = np.vstack((A, B))
C

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [112]:
C.shape

(6, 3)

In [114]:
D = np.hstack((A,B))
D

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [116]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [118]:
d = np.column_stack((a,b,c))
d

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [119]:
e = np.row_stack((a,b,c))
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])